const ERROR_CODES = {
  // Don't use 0 since it's false-y and is fertile grounds for programming error
  UNEXPECTER_ERROR: -1,
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

  // GENERAL
  INVALID_API_PARAMS: "INVALID_API_PARAMS",

  // OTP
  INVALID_OTP: "INVALID_OTP",
  EXPIRED_OTP: "EXPIRED_OTP",
  RESOLVED_OTP: "RESOLVED_OTP",
  INVALID_ACTION: "INVALID_ACTION",

  // Dealing with room logic
  JOIN_FAIL_NO_SUCH_USER: 'JOIN_FAIL_NO_SUCH_USER',
  JOIN_ALREADY_MEMBER: 'JOIN_ALREADY_MEMBER',
  TOO_MANY_OWNED_ROOMS: "TOO_MANY_OWNED_ROOMS",
  ALREADY_INVITED: "ALREADY_INVITED",
  UNKNOWN_ROOM: "UNKNOWN_ROOM",
  CLAIM_UNIQUENESS: "CLAIM_UNIQUENESS",
  CANT_INVITE_SELF: "CANT_INVITE_SELF",
  INVALID_ROOM_CLAIM: "INVALID_ROOM_CLAIM",
  UNAUTHORIZED_ROOM_ACCESS: "UNAUTHORIZED_ROOM_ACCESS",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  INVALID_INVITE: "INVALID_INVITE",
  TOO_MANY_INVITES: "TOO_MANY_INVITES",
  INCORRECT_ROOM_PASSCODE: "INCORRECT_ROOM_PASSCODE",
  INVALID_USER_IDENTITY: "INVALID_USER_IDENTITY",
  PERMISSION_DENIED: "PERMISSION_DENIED",
  TOO_MANY_ROOM_MEMBERS: "TOO_MANY_ROOM_MEMBERS",

  // User logic
  // We prefer string error codes but thave not yet fully migrated towards them
  ALREADY_REGISTERED: 1,
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
  ADMIN_ONLY_RESTRICTED: "ADMIN_ONLY_RESTRICTED",
  NO_SUCH_USER: "NO_SUCH_USER",

  // DEPRECATED
  UNAUTHORIZED: "UNAUTHORIZED_USER",
}

module.exports = {
  code: ERROR_CODES
}
