module.exports = {
  MESSAGE_INVALID_FORMAT: "MESSAGE_INVALID_FORMAT",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  EVENT_TYPE_INVALID: "EVENT_TYPE_INVALID",
  UNAUTHORIZED: "UNAUTHORIZED",
  AUTH_FAILED: "AUTH_FAILED",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  NO_DEFAULT_ROOM: "NO_DEFAULT_ROOM",

  TOO_MANY_PARTICIPANTS: "TOO_MANY_PARTICIPANTS",
}
