export enum ErrorTypes {
  INVALID_ROOM_PERMISSIONS = 'INVALID_ROOM_PERMISSIONS',
  LINK_EXPIRED = 'LINK_EXPIRED',
  PAGE_NOT_FOUND = 'PAGE_NOT_FOUND',
  ROOM_NOT_FOUND = 'ROOM_NOT_FOUND',
  UNEXPECTED = 'UNEXPECTED',
}
