// TODO: finialize error codes with Alexy and bring this up to standard
export enum ErrorCodes {
  JOIN_FAIL_NO_SUCH_USER = 1,
  JOIN_ALREADY_MEMBER = 2,
  UNKNOWN_ROOM = 'UNKNOWN_ROOM',
  UNAUTHORIZED = 'UNAUTHORIZED',
  UNAUTHORIZED_ROOM_ACCESS = 'UNAUTHORIZED_ROOM_ACCESS',
  INCORRECT_ROOM_PASSCODE = 'INCORRECT_ROOM_PASSCODE',
  INVALID_USER_IDENTITY = 'INVALID_USER_IDENTITY',
}
