export enum RouteNames {
  ROOT = '/',
  SIGN_UP = '/signup',
  SIGN_IN = '/signin',
  ENABLE_ADMIN = '/1_secret_2_admin_3_enabler_4',
  COMPLETE_SIGNUP = '/complete_signup',
  LOGIN_IN_WITH_EMAIL = '/loginwithemail',
  SUBSCRIBE = '/subscribe',
  UNSUBSCRIBE = '/unsubscribe',
  FEATURE_FLAGS = '/internal/featureflags',
  LICENSES = '/licenses',
  MEETING_LINK = '/meetinglink',
  CREATE_MEETING = '/create',
  CREATE_MEETING_URL = '/create/:meetingType',
}
