export const WallpaperMetadata = [
  { name: 'Abstract_Space' },
  { name: 'Activity' },
  { name: 'Fall_Leaves' },
  { name: 'Geometric_1' },
  { name: 'Geometric_2' },
  { name: 'Geometric_3' },
  { name: 'Green_Leaves' },
  { name: 'Koi_Pond' },
  { name: 'Spring_Flowers' },
  { name: '2_Week_Schedule_Apple' },
  { name: '3_Boards_Eucalyptus' },
  { name: '3_Boards_Pink_Hill' },
  { name: '6_Boards_Leaves' },
  { name: 'Calendar_Cactus' },
  { name: 'To-Do_Board_Blue_Hill' },
  { name: 'To-Do_Board_Flowers' },
  { name: 'To-Do_Board_Lemons' },
  { name: 'To-Do_Board_Mushrooms' },
  { name: 'Venn_Diagram_Leaves' },
  { name: 'Weekly_Schedule_Donut' },
  { name: 'Weekly_Schedule_Fall_Leaves' },
];
