module.exports = {
  // Don't use 0 since it's false-y and is fertile grounds for programming error
  UNEXPECTER_ERROR: -1,
  otp: {
    INVALID_OTP: 1,
    EXPIRED_OTP: 2,
    RESOLVED_OTP: 3,
    INVALID_ACTION: "INVALID_ACTION",
  },

  room: {
    // TODO: migrate all error codes to strings
    JOIN_FAIL_NO_SUCH_USER: 1,
    JOIN_ALREADY_MEMBER: 2,
    TOO_MANY_OWNED_ROOMS: "TOO_MANY_OWNED_ROOMS",
    ALREADY_INVITED: "ALREADY_INVITED",
    UNKNOWN_ROOM: "UNKNOWN_ROOM",
    CLAIM_UNIQUENESS: "CLAIM_UNIQUENESS",
    CANT_INVITE_SELF: "CANT_INVITE_SELF",
    INVALID_ROOM_CLAIM: "INVALID_ROOM_CLAIM",
    UNAUTHORIZED_ROOM_ACCESSS: "UNAUTHORIZED_ROOM_ACCESSS",
    ALREADY_CLAIMED: "ALREADY_CLAIMED",
    INVALID_INVITE: "INVALID_INVITE",
    TOO_MANY_INVITES: "TOO_MANY_INVITES",
    UNAUTHORIZED: 'UNAUTHORIZED', // TODO: this may not be used anymore
    INCORRECT_ROOM_PASSCODE: 'INCORRECT_ROOM_PASSCODE',
    INVALID_USER_IDENTITY: 'INVALID_USER_IDENTITY',
  },

  user: {
    ALREADY_REGISTERED: 1,
    // We prefer string error codes but thave not yet fully migrated towards them
    UNAUTHORIZED: "UNAUTHORIZED_USER",
    ADMIN_ONLY_RESTRICTED: "ADMIN_ONLY_RESTRICTED",
    NO_SUCH_USER: "NO_SUCH_USER"
  }
}
