const ERROR_CODES = {
  // Don't use 0 since it's false-y and is fertile grounds for programming error
  UNEXPECTER_ERROR: -1,

  INVALID_API_PARAMS:'INVALID_API_PARAMS',

  INVALID_OTP: "INVALID_OTP",
  EXPIRED_OTP: "EXPIRED_OTP",
  RESOLVED_OTP: "RESOLVED_OTP",
  REVOKED_OTP: "REVOKED_OTP",
  MAGIC_LINK_INVALID_ACTION: "INVALID_ACTION",

  OPENGRAPH_NO_DATA: "NO_OPENGRAPH_DATA",

  // Dealing with room logic
  JOIN_FAIL_NO_SUCH_USER: 'JOIN_FAIL_NO_SUCH_USER',
  JOIN_ALREADY_MEMBER: 'JOIN_ALREADY_MEMBER',
  TOO_MANY_OWNED_ROOMS: "TOO_MANY_OWNED_ROOMS",
  ALREADY_INVITED: "ALREADY_INVITED",
  UNKNOWN_ROOM: "UNKNOWN_ROOM",
  CLAIM_UNIQUENESS: "CLAIM_UNIQUENESS",
  CANT_INVITE_SELF: "CANT_INVITE_SELF",
  INVALID_ROOM_CLAIM: "INVALID_ROOM_CLAIM",
  UNAUTHORIZED_ROOM_ACCESS: "UNAUTHORIZED_ROOM_ACCESS",
  ALREADY_CLAIMED: "ALREADY_CLAIMED",
  INVALID_INVITE: "INVALID_INVITE",
  TOO_MANY_INVITES: "TOO_MANY_INVITES",
  INCORRECT_ROOM_PASSCODE: 'INCORRECT_ROOM_PASSCODE',
  INVALID_USER_IDENTITY: 'INVALID_USER_IDENTITY',

  // Permissions
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // User logic
  ALREADY_REGISTERED: "ALREADY_REGISTERED",
  // We prefer string error codes but thave not yet fully migrated towards them
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
  ADMIN_ONLY_RESTRICTED: "ADMIN_ONLY_RESTRICTED",
  NO_SUCH_USER: "NO_SUCH_USER",

  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // DEPRECATED
  UNAUTHORIZED: "UNAUTHORIZED_USER", // use UNAUTHORIZED_USER
}

// I want to transition to shared.lib.error.code vs shared.lib.errors.code,
// but I think mercury currently references the old style
module.exports = {
  code: ERROR_CODES
}
